"""Submission drafts — finding → program-format report (v0.5).

The report-writer doctrine (impact-first, no theoretical language, no
"could potentially") productised as a deterministic template so a run's
findings leave the machine one `avci submit` away from the program's
inbox. Refuted findings are skipped; PII is redacted the same way the
markdown report does it.
"""

from __future__ import annotations

import re
from pathlib import Path

from ..vulns.triage import redact_pii

# suggested CVSS 3.1 vectors per severity — the operator adjusts before
# submitting; the draft never invents precision it doesn't have
_CVSS = {
    "critical": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H (9.8)",
    "high": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N (7.5)",
    "medium": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N (6.5)",
    "low": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N (3.7)",
    "info": "— (informational)",
}

_PLATFORM = {
    "generic": {
        "title": "Bug report", "labels": "## {}",
    },
    "intigriti": {
        "title": "Intigriti submission",
        "labels": "## {}",
        "extra": ("\n> Draft for Intigriti — paste into the submission form.\n"
                  "> Impact-first, verbatim evidence, no theoretical language.\n"),
    },
    "h1": {
        "title": "HackerOne submission",
        "labels": "## {}",
        "extra": ("\n> Draft for HackerOne — summary → impact → steps →\n"
                  "> supporting material order.\n"),
    },
}


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:60] or "finding"


def build_submission(f, run_id: str = "", platform: str = "generic",
                     keep_hosts: list[str] | None = None) -> str:
    """One finding → one submission markdown (deterministic, no LLM)."""
    plat = _PLATFORM.get(platform, _PLATFORM["generic"])
    sev = (f.severity or "medium").lower()
    title = f.title or "Untitled finding"
    red = lambda t: redact_pii(t or "", keep_hosts=keep_hosts)  # noqa: E731
    lines = [
        f"# [{sev.upper()}] {title}",
        "",
        f"*Draft generated by AVCI from run `{run_id}`"
        + (f" — {plat['title']}" if platform != "generic" else "") + "*",
        plat.get("extra", "").rstrip(),
        "",
        plat["labels"].format("Summary"),
        red(f.description or "").strip() or "—",
        "",
        plat["labels"].format("Impact"),
        _impact(sev),
        "",
        plat["labels"].format("Steps to reproduce"),
        _steps(f),
        "",
        plat["labels"].format("Evidence (verbatim)"),
        "```",
        red(f.evidence or "").strip()[:4000] or "—",
        "```",
    ]
    poc = (f.poc or "").strip() if hasattr(f, "poc") else ""
    if poc:
        lines += ["", plat["labels"].format("Proof of concept"),
                  "```", red(poc)[:4000], "```"]
    lines += [
        "",
        plat["labels"].format("Remediation"),
        _remediation(f),
        "",
        plat["labels"].format("Severity / CVSS"),
        f"Suggested: {sev.upper()} — {_CVSS.get(sev, _CVSS['medium'])}"
        + (f" · CWE {f.cwe}" if getattr(f, "cwe", "") else ""),
        "",
    ]
    return "\n".join(lines)


def _impact(sev: str) -> str:
    return {
        "critical": ("Direct compromise of confidentiality, integrity and/or "
                     "availability as demonstrated — server-side code "
                     "execution, authentication bypass or full data exposure "
                     "on the affected component."),
        "high": ("Able to read or modify data beyond authorization as "
                 "demonstrated — cross-tenant access, credential exposure, "
                 "or stored payload execution in a victim's session."),
        "medium": ("Security control bypass with limited blast radius as "
                   "demonstrated — information disclosure aiding further "
                   "attacks or client-side impact requiring interaction."),
        "low": ("Minimal direct impact as demonstrated — hygiene issue that "
                "weakens defense in depth and enables other issues."),
        "info": "Informational — no direct security impact demonstrated.",
    }.get(sev, "")


def _steps(f) -> str:
    url = getattr(f, "url", "") or ""
    out = []
    if url:
        out.append(f"1. Navigate to `{url}`")
    ev = (f.evidence or "").strip()
    if ev:
        first = ev.splitlines()[0][:160]
        out.append(f"2. Issue the request / interaction below — observed "
                   f"response (first line): `{first}`")
    out.append("3. Observe the verbatim evidence section — the response is "
               "reproducible as shown.")
    return "\n".join(out) or "—"


def _remediation(f) -> str:
    cwe = (getattr(f, "cwe", "") or "").lower()
    if "79" in cwe or "xss" in (f.title or "").lower():
        return ("Context-aware output encoding and input validation on the "
                "reflected parameter; CSP as a second line of defense.")
    if "89" in cwe or "sql" in (f.title or "").lower():
        return ("Parameterized queries / prepared statements for the "
                "affected parameter; least-privilege DB account.")
    if "639" in cwe or "idor" in (f.title or "").lower() or \
            "bola" in (f.title or "").lower():
        return ("Enforce object-level authorization on every request — "
                "validate the session identity against the resource owner "
                "server-side, use non-sequential identifiers.")
    if "200" in cwe or "disclos" in (f.title or "").lower():
        return ("Remove the exposed artifact from the web root; rotate any "
                "leaked credentials; disable debug output in production.")
    return ("Validate the affected input server-side, enforce authorization "
            "at the object level, and add regression tests for the "
            "demonstrated vector.")


def write_submissions(state, run_dir: Path, only: str = "",
                      platform: str = "generic") -> list[Path]:
    """Draft every live (non-refuted) finding in run_dir/submissions/."""
    keep_hosts = [str(x) for x in (getattr(state, "scope", None) or [])]
    out_dir = Path(run_dir) / "submissions"
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    n = 0
    for f in state.findings:
        if getattr(f, "verdict", "") == "refuted":
            continue
        if only and only.lower() not in (f.title or "").lower():
            continue
        n += 1
        md = build_submission(f, run_id=getattr(state, "run_id", ""),
                              platform=platform, keep_hosts=keep_hosts)
        path = out_dir / f"{n:02d}-{_slug(f.title or 'finding')}.md"
        path.write_text(md, encoding="utf-8")
        written.append(path)
    return written
